hostname = as.sigma.run, api.sigma.run

# Sigma卡路里抢兑
# 拦截home接口显示库存，拦截redeem接口快速重放200次
^https?://[^/]+/quidd/kcal/act/home url script-response-body sigma_seckill.js
^https?://[^/]+/quidd/kcal/act/redeem$ url script-request-body sigma_seckill.js
