# =========================
# Wise DIRECT（Quantumult X）
# =========================
# 更新日期: 2026-07-06
HOST-SUFFIX,wise.com,DIRECT
HOST-SUFFIX,transferwise.com,DIRECT
HOST-SUFFIX,wise.tech,DIRECT
HOST-SUFFIX,wise.jobs,DIRECT
HOST-SUFFIX,wise-b.com,DIRECT
HOST-SUFFIX,wise-assets.com,DIRECT
HOST-SUFFIX,transferwise.tech,DIRECT
HOST-SUFFIX,wisepayments.com,DIRECT
HOST-SUFFIX,sendwise.com,DIRECT
HOST-SUFFIX,wiseplatform.com,DIRECT
HOST,wise.com,DIRECT
HOST,api.wise.com,DIRECT
HOST,api.transferwise.com,DIRECT
HOST,login.wise.com,DIRECT
HOST,wise-platform.com,DIRECT
