hostname = img.meituan.net, s3plus.meituan.net, flowplus.meituan.net

# 美团 & 美团外卖 去广告规则

# 开屏/弹窗
^https?:\/\/wmapi\.meituan\.com\/api\/v7\/(loadInfo|openscreen|startpicture)\? url reject-dict

# 动图/视频广告
^https?:\/\/(s3plus|flowplus)\.meituan\.net\/v\d\/\w+\/linglong\/\w+\.(gif|jpg|mp4) url reject-img

# 品牌广告图
^https?:\/\/img\.meituan\.net\/bizad\/bizad_brandCpt_\d+\.jpg url reject-img

# 商品奖品图
^https?:\/\/img\.meituan\.net\/goodsawardpic\/[a-f0-9]+\.png\.webp url reject-img

# 区块配置广告
^https?:\/\/s3plus\.meituan\.net\/ocean-blk-index\/index\/blk_conf_73\.json url reject-dict

# 品牌/外卖广告包
^https?:\/\/s3plus\.meituan\.net\/v1\/mss_\w+\/(brandcpt-vedio|waimai-alita)\/\w+\.zip$ url reject-dict

# AMDC 分发
^http:\/\/59\.82\.113\.10\/amdc\/mobileDispatch\?appkey=213807& url reject-dict

# HOST 级别拒绝（统计/分析/广告域名）
host-suffix, meituan.xn, reject
host-suffix, meituan.yoga, reject
host-suffix, meituangov.cn, reject
host-suffix, report.meituan.com, reject
host-suffix, analytics.meituan.net, reject
host-suffix, wmlog.meituan.com, reject
host-suffix, ad.e.waimai.sankuai.com, reject
host-suffix, mads.meituan.com, reject
host-suffix, dreport.meituan.net, reject
host-suffix, d.meituan.net, reject